# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f2b7df60e97649de18a9d3fd50c2502d"
name = "content-generator"
handle = "content-generator-5"
application_url = "https://shpify-ai-content-generator.onrender.com"
embedded = true

[build]
include_config_on_deploy = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://shpify-ai-content-generator.onrender.com/auth/callback",
  "https://shpify-ai-content-generator.onrender.com/auth/shopify/callback",
  "https://shpify-ai-content-generator.onrender.com/api/auth/callback"
]
[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  uri = "pubsub://content-generator:content"
  compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]

[pos]
embedded = false
